# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-09 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_delete_userask'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='sender',
            field=models.IntegerField(default=0, verbose_name='\u53d1\u51fa\u7528\u6237'),
        ),
    ]
