# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-08 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='click_num',
        ),
        migrations.RemoveField(
            model_name='course',
            name='fav_nums',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_banner',
        ),
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
    ]
