# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-09 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_click_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='detail',
            field=models.CharField(max_length=300, verbose_name='\u8bfe\u7a0b\u8be6\u60c5'),
        ),
    ]
