# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-09 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20170609_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fav_nums',
            field=models.IntegerField(default=0, verbose_name='\u6536\u85cf\u4eba\u6570'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.IntegerField(default=0, verbose_name='\u5b66\u4e60\u4eba\u6570'),
        ),
    ]
