# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-24 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20170609_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher_tell',
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('sf', '\u7b97\u6cd5'), ('pt', 'python\u8bed\u6cd5'), ('ap', '\u5e94\u7528'), ('zn', '\u4eba\u5de5\u667a\u80fd'), ('ot', '\u5176\u4ed6')], default='ot', max_length=20, verbose_name='\u8bfe\u7a0b\u6807\u7b7e'),
        ),
    ]
