# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-24 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20170624_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='category',
            new_name='tag',
        ),
    ]
