# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-08 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_teacher_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='teacher_role',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='teacher_id',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='\u6559\u5e08id'),
        ),
    ]
